/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** サービス死活監視 (ClusterIP 内部のみ) */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全カード定義を返す (battle / gateway 起動時キャッシュロード用) */
        get: operations["listCards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cards/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** プレイヤーの所持カード一覧を返す */
        get: operations["listPlayerCards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cards/cards/with-ownership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全カード定義にプレイヤーの所持状態を付与して返す */
        get: operations["listCardsWithOwnership"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cards/decks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** プレイヤーのデッキ一覧を返す */
        get: operations["listDecks"];
        put?: never;
        /** 新しいデッキを作成する */
        post: operations["createDeck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cards/decks/{deckId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 指定デッキの詳細 (カード構成を含む) を返す */
        get: operations["getDeck"];
        /** 既存デッキを更新する */
        put: operations["updateDeck"];
        post?: never;
        /** デッキを削除する */
        delete: operations["deleteDeck"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cards/decks/{deckId}/validate-for-battle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** デッキがバトル使用可能か検証する (カード所持・制限・枚数チェック) */
        post: operations["validateDeckForBattle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        CardDefinition: {
            card_id: string;
            card_name: string;
            resource_label: string;
            /** @description ファクション (`SHE` / `Tenki` / `Sugar` / `Tuners` / `Neutral`) */
            faction: string;
            /** @description カード種別 */
            card_type: string;
            /** @description サブタイプ (Compute/Data 配下のみ) */
            subtype?: string;
            /**
             * Format: int64
             * @description デプロイターン数 (0=即時)
             */
            deploy_turns: number;
            /** @description 手動スケール可能か */
            resizable: boolean;
            /** @description 自動スケール対応か */
            elastic: boolean;
            /** Format: int64 */
            elastic_increment?: number;
            /** Format: int64 */
            free_tier?: number;
            /** Format: int64 */
            cost_per_request?: number;
            /** @description スタッツ (ComputeStats または DataStats) */
            stats: {
                [key: string]: unknown;
            };
            effect_text?: string;
            /** @description エフェクト定義 JSON */
            effects?: {
                [key: string]: unknown;
            };
            passive_effects?: components["schemas"]["PassiveEffect"][];
            platform_effects?: components["schemas"]["PlatformEffect"][];
            attachment_effects?: components["schemas"]["AttachmentEffect"][];
            /** @description 制限区分 (`unlimited` / `semi_limited` / `limited` / `forbidden`) */
            restriction: string;
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description CardDefinition にプレイヤー所持状態を付与した型。 */
        CardWithOwnership: {
            card_id: string;
            card_name: string;
            resource_label: string;
            faction: string;
            card_type: string;
            subtype?: string;
            /** Format: int64 */
            deploy_turns: number;
            resizable: boolean;
            elastic: boolean;
            /** Format: int64 */
            elastic_increment?: number;
            /** Format: int64 */
            free_tier?: number;
            /** Format: int64 */
            cost_per_request?: number;
            stats: {
                [key: string]: unknown;
            };
            effect_text?: string;
            effects?: {
                [key: string]: unknown;
            };
            passive_effects?: components["schemas"]["PassiveEffect"][];
            platform_effects?: components["schemas"]["PlatformEffect"][];
            attachment_effects?: components["schemas"]["AttachmentEffect"][];
            restriction: string;
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            is_owned: boolean;
        };
        /** @description プレイヤー所持カードにカード定義フィールドを付加した API レスポンス型。 */
        PlayerCardWithDef: {
            card_id: string;
            /** Format: int64 */
            art_no: number;
            /** @description 所持枚数 */
            count: number;
            card_name: string;
            resource_label: string;
            faction: string;
            card_type: string;
            subtype?: string;
            /** Format: int64 */
            deploy_turns: number;
            resizable: boolean;
            elastic: boolean;
            stats: {
                [key: string]: unknown;
            };
            effect_text?: string;
            restriction: string;
        };
        /** @description Compute / Container / Orchestrator / Serverless / AI/ML カード用スタッツ。 */
        ComputeStats: {
            /** Format: int64 */
            throughput: number;
            /** Format: int64 */
            throughput_max?: number;
            /** Format: int64 */
            availability: number;
            /** Format: int64 */
            maintenance_cost: number;
            /** Format: int64 */
            sla_penalty: number;
        };
        /** @description Database / ObjectStorage / CacheDB カード用スタッツ。 */
        DataStats: {
            /** Format: int64 */
            yield: number;
            /** Format: int64 */
            yield_max?: number;
            /** Format: int64 */
            availability: number;
            /** Format: int64 */
            maintenance_cost: number;
            /** Format: int64 */
            sla_penalty: number;
        };
        PassiveEffect: {
            type: components["schemas"]["PassiveEffectType"];
            params: {
                [key: string]: unknown;
            };
        };
        PlatformEffect: {
            type: components["schemas"]["PlatformEffectType"];
            params: {
                [key: string]: unknown;
            };
        };
        AttachmentEffect: {
            type: components["schemas"]["AttachmentEffectType"];
            params: {
                [key: string]: unknown;
            };
        };
        /** @description プレイヤーのデッキ (カード構成オプショナル)。 */
        Deck: {
            player_id: string;
            /**
             * Format: int64
             * @description デッキ ID (自動採番)
             */
            deck_id: number;
            deck_name: string;
            /** @description バトル使用可能か (都度算出) */
            is_valid: boolean;
            /** Format: int64 */
            playmat_no?: number;
            /** Format: int64 */
            sleeve_no?: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** @description デッキのカード構成 (API レスポンス時に populate) */
            deck_cards?: components["schemas"]["DeckCard"][];
        };
        DeckCard: {
            player_id: string;
            /** Format: int64 */
            deck_id: number;
            card_id: string;
            /** Format: int64 */
            art_no: number;
            count: number;
        };
        /** @description デッキ作成・更新リクエスト内のカードエントリ。 */
        DeckCardEntry: {
            card_id: string;
            /** Format: int64 */
            art_no: number;
            count: number;
        };
        DeckCreateRequest: {
            deck_name: string;
            cards: components["schemas"]["DeckCardEntry"][];
            /** Format: int64 */
            playmat_no?: number;
            /** Format: int64 */
            sleeve_no?: number;
        };
        DeckUpdateRequest: {
            deck_name: string;
            cards: components["schemas"]["DeckCardEntry"][];
            /** Format: int64 */
            playmat_no?: number;
            /** Format: int64 */
            sleeve_no?: number;
        };
        /** @description GET /players/{playerId}/decks/{deckId} のレスポンス封筒。 */
        DeckDetailResponse: {
            deck: components["schemas"]["Deck"];
            cards: components["schemas"]["DeckCard"][];
        };
        /**
         * @description パッシブエフェクトの種別。
         * @enum {string}
         */
        PassiveEffectType: "tp_per_backend_db" | "tp_per_backend_data" | "tp_if_card_type_on_field" | "dv_per_other_db" | "dv_if_card_on_field" | "av_bonus" | "scale_cost_free";
        /**
         * @description プラットフォームエフェクトの種別。
         * @enum {string}
         */
        PlatformEffectType: "tp_bonus" | "yield_bonus" | "av_bonus";
        /**
         * @description アタッチメントエフェクトの種別。
         * @enum {string}
         */
        AttachmentEffectType: "stat_bonus";
    };
    responses: never;
    parameters: {
        DeckIdPath: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listCards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description カード定義一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDefinition"][];
                };
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPlayerCards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 所持カード一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerCardWithDef"][];
                };
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCardsWithOwnership: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 所持状態付きカード一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardWithOwnership"][];
                };
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listDecks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description デッキ一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"][];
                };
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description プレイヤーが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createDeck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckCreateRequest"];
            };
        };
        responses: {
            /** @description 作成されたデッキ */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            /** @description リクエストボディ不正 / デッキバリデーション失敗 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 未所持カードを含む */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDeck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deckId: components["parameters"]["DeckIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description デッキ詳細 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckDetailResponse"];
                };
            };
            /** @description deckId が不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description デッキが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateDeck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deckId: components["parameters"]["DeckIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新されたデッキ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            /** @description deckId 不正 / リクエストボディ不正 / デッキバリデーション失敗 / 制限枚数超過 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 未所持カードを含む */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description デッキが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteDeck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deckId: components["parameters"]["DeckIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除成功 (ボディなし) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description deckId が不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description デッキが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    validateDeckForBattle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deckId: components["parameters"]["DeckIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 検証成功 (ボディなし) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description deckId 不正 / デッキバリデーション失敗 / 制限枚数超過 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 未所持カードを含む */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description デッキが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 接続エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
