// Code generated by scripts/generate_types.py; DO NOT EDIT.

package apicard

import (
	"encoding/json"
	"time"
)

// CardWithOwnership is a CardDefinition enriched with per-player ownership flag.
type CardWithOwnership struct {
	CardID            string             `json:"card_id"`
	CardName          string             `json:"card_name"`
	ResourceLabel     string             `json:"resource_label"`
	Faction           string             `json:"faction"`
	CardType          string             `json:"card_type"`
	Subtype           *string            `json:"subtype,omitempty"`
	DeployTurns       int64              `json:"deploy_turns"`
	Resizable         bool               `json:"resizable"`
	Elastic           bool               `json:"elastic"`
	ElasticIncrement  int64              `json:"elastic_increment,omitempty"`
	FreeTier          int64              `json:"free_tier,omitempty"`
	CostPerRequest    int64              `json:"cost_per_request,omitempty"`
	Stats             json.RawMessage    `json:"stats"`
	EffectText        *string            `json:"effect_text,omitempty"`
	Effects           json.RawMessage    `json:"effects,omitempty"`
	PassiveEffects    []PassiveEffect    `json:"passive_effects,omitempty"`
	PlatformEffects   []PlatformEffect   `json:"platform_effects,omitempty"`
	AttachmentEffects []AttachmentEffect `json:"attachment_effects,omitempty"`
	Restriction       string             `json:"restriction"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	IsOwned           bool               `json:"is_owned"`
}

