// Code generated by scripts/generate_types.py; DO NOT EDIT.

package apicard

// GrantPackRequest is the request body for grant-initial-pack / grant-faction-pack.
type GrantPackRequest struct {
	Faction string `json:"faction"`
}

// GrantPackResponse is the response for grant-initial-pack / grant-faction-pack.
type GrantPackResponse struct {
	CardsGranted int `json:"cardsGranted"`
}

