// Package apicard provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apicard

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	InternalAuthScopes internalAuthContextKey = "InternalAuth.Scopes"
)

// Defines values for AttachmentEffectType.
const (
	AttachmentEffectTypeStatBonus AttachmentEffectType = "stat_bonus"
)

// Valid indicates whether the value is a known member of the AttachmentEffectType enum.
func (e AttachmentEffectType) Valid() bool {
	switch e {
	case AttachmentEffectTypeStatBonus:
		return true
	default:
		return false
	}
}

// Defines values for PassiveEffectType.
const (
	PassiveEffectTypeAvBonus             PassiveEffectType = "av_bonus"
	PassiveEffectTypeDvIfCardOnField     PassiveEffectType = "dv_if_card_on_field"
	PassiveEffectTypeDvPerOtherDb        PassiveEffectType = "dv_per_other_db"
	PassiveEffectTypeScaleCostFree       PassiveEffectType = "scale_cost_free"
	PassiveEffectTypeTpIfCardTypeOnField PassiveEffectType = "tp_if_card_type_on_field"
	PassiveEffectTypeTpPerBackendData    PassiveEffectType = "tp_per_backend_data"
	PassiveEffectTypeTpPerBackendDb      PassiveEffectType = "tp_per_backend_db"
)

// Valid indicates whether the value is a known member of the PassiveEffectType enum.
func (e PassiveEffectType) Valid() bool {
	switch e {
	case PassiveEffectTypeAvBonus:
		return true
	case PassiveEffectTypeDvIfCardOnField:
		return true
	case PassiveEffectTypeDvPerOtherDb:
		return true
	case PassiveEffectTypeScaleCostFree:
		return true
	case PassiveEffectTypeTpIfCardTypeOnField:
		return true
	case PassiveEffectTypeTpPerBackendData:
		return true
	case PassiveEffectTypeTpPerBackendDb:
		return true
	default:
		return false
	}
}

// Defines values for PlatformEffectType.
const (
	PlatformEffectTypeAvBonus    PlatformEffectType = "av_bonus"
	PlatformEffectTypeTpBonus    PlatformEffectType = "tp_bonus"
	PlatformEffectTypeYieldBonus PlatformEffectType = "yield_bonus"
)

// Valid indicates whether the value is a known member of the PlatformEffectType enum.
func (e PlatformEffectType) Valid() bool {
	switch e {
	case PlatformEffectTypeAvBonus:
		return true
	case PlatformEffectTypeTpBonus:
		return true
	case PlatformEffectTypeYieldBonus:
		return true
	default:
		return false
	}
}

// AttachmentEffect defines model for AttachmentEffect.
type AttachmentEffect struct {
	Params map[string]interface{} `json:"params"`

	// Type アタッチメントエフェクトの種別。
	Type AttachmentEffectType `json:"type"`
}

// AttachmentEffectType アタッチメントエフェクトの種別。
type AttachmentEffectType string

// CardDefinition defines model for CardDefinition.
type CardDefinition struct {
	AttachmentEffects *[]AttachmentEffect `json:"attachment_effects,omitempty"`
	CardID            string              `json:"card_id"`
	CardName          string              `json:"card_name"`

	// CardType カード種別
	CardType       string    `json:"card_type"`
	CostPerRequest *int64    `json:"cost_per_request,omitempty"`
	CreatedAt      time.Time `json:"created_at"`

	// DeployTurns デプロイターン数 (0=即時)
	DeployTurns int64   `json:"deploy_turns"`
	EffectText  *string `json:"effect_text,omitempty"`

	// Effects エフェクト定義 JSON
	Effects *json.RawMessage `json:"effects,omitempty"`

	// Elastic 自動スケール対応か
	Elastic          bool   `json:"elastic"`
	ElasticIncrement *int64 `json:"elastic_increment,omitempty"`

	// Faction ファクション (`SHE` / `Tenki` / `Sugar` / `Tuners` / `Neutral`)
	Faction         string            `json:"faction"`
	FreeTier        *int64            `json:"free_tier,omitempty"`
	IsActive        bool              `json:"is_active"`
	PassiveEffects  *[]PassiveEffect  `json:"passive_effects,omitempty"`
	PlatformEffects *[]PlatformEffect `json:"platform_effects,omitempty"`

	// Resizable 手動スケール可能か
	Resizable     bool   `json:"resizable"`
	ResourceLabel string `json:"resource_label"`

	// Restriction 制限区分 (`unlimited` / `semi_limited` / `limited` / `forbidden`)
	Restriction string `json:"restriction"`

	// Stats スタッツ (ComputeStats または DataStats)
	Stats json.RawMessage `json:"stats"`

	// Subtype サブタイプ (Compute/DataResource 配下のみ)
	Subtype   *string   `json:"subtype,omitempty"`
	UpdatedAt time.Time `json:"updated_at"`
}

// CardWithOwnership CardDefinition にプレイヤー所持状態を付与した型。
type CardWithOwnership struct {
	AttachmentEffects *[]AttachmentEffect `json:"attachment_effects,omitempty"`
	CardID            string              `json:"card_id"`
	CardName          string              `json:"card_name"`
	CardType          string              `json:"card_type"`
	CostPerRequest    *int64              `json:"cost_per_request,omitempty"`
	CreatedAt         time.Time           `json:"created_at"`
	DeployTurns       int64               `json:"deploy_turns"`
	EffectText        *string             `json:"effect_text,omitempty"`
	Effects           *json.RawMessage    `json:"effects,omitempty"`
	Elastic           bool                `json:"elastic"`
	ElasticIncrement  *int64              `json:"elastic_increment,omitempty"`
	Faction           string              `json:"faction"`
	FreeTier          *int64              `json:"free_tier,omitempty"`
	IsActive          bool                `json:"is_active"`
	IsOwned           bool                `json:"is_owned"`
	PassiveEffects    *[]PassiveEffect    `json:"passive_effects,omitempty"`
	PlatformEffects   *[]PlatformEffect   `json:"platform_effects,omitempty"`
	Resizable         bool                `json:"resizable"`
	ResourceLabel     string              `json:"resource_label"`
	Restriction       string              `json:"restriction"`
	Stats             json.RawMessage     `json:"stats"`
	Subtype           *string             `json:"subtype,omitempty"`
	UpdatedAt         time.Time           `json:"updated_at"`
}

// ComputeStats Compute / Container / Orchestrator / Serverless / AI/ML カード用スタッツ。
type ComputeStats struct {
	Availability    int64  `json:"availability"`
	MaintenanceCost int64  `json:"maintenance_cost"`
	SLAPenalty      int64  `json:"sla_penalty"`
	Throughput      int64  `json:"throughput"`
	ThroughputMax   *int64 `json:"throughput_max,omitempty"`
}

// DataStats Database / ObjectStorage / CacheDB カード用スタッツ。
type DataStats struct {
	Availability    int64  `json:"availability"`
	MaintenanceCost int64  `json:"maintenance_cost"`
	SLAPenalty      int64  `json:"sla_penalty"`
	Yield           int64  `json:"yield"`
	YieldMax        *int64 `json:"yield_max,omitempty"`
}

// Deck プレイヤーのデッキ (カード構成オプショナル)。
type Deck struct {
	CreatedAt time.Time `json:"created_at"`

	// DeckCards デッキのカード構成 (API レスポンス時に populate)
	DeckCards *[]DeckCard `json:"deck_cards,omitempty"`

	// DeckID デッキ ID (自動採番)
	DeckID   int64  `json:"deck_id"`
	DeckName string `json:"deck_name"`

	// IsValid バトル使用可能か (都度算出)
	IsValid   bool      `json:"is_valid"`
	PlayerID  string    `json:"player_id"`
	PlaymatNo *int64    `json:"playmat_no,omitempty"`
	SleeveNo  *int64    `json:"sleeve_no,omitempty"`
	UpdatedAt time.Time `json:"updated_at"`
}

// DeckCard defines model for DeckCard.
type DeckCard struct {
	ArtNo    int64  `json:"art_no"`
	CardID   string `json:"card_id"`
	Count    int    `json:"count"`
	DeckID   int64  `json:"deck_id"`
	PlayerID string `json:"player_id"`
}

// DeckCardEntry デッキ作成・更新リクエスト内のカードエントリ。
type DeckCardEntry struct {
	ArtNo  int64  `json:"art_no"`
	CardID string `json:"card_id"`
	Count  int    `json:"count"`
}

// DeckCreateRequest defines model for DeckCreateRequest.
type DeckCreateRequest struct {
	Cards     []DeckCardEntry `json:"cards"`
	DeckName  string          `json:"deck_name"`
	PlaymatNo *int64          `json:"playmat_no,omitempty"`
	SleeveNo  *int64          `json:"sleeve_no,omitempty"`
}

// DeckDetailResponse GET /players/{playerId}/decks/{deckId} のレスポンス封筒。
type DeckDetailResponse struct {
	Cards []DeckCard `json:"cards"`

	// Deck プレイヤーのデッキ (カード構成オプショナル)。
	Deck Deck `json:"deck"`
}

// DeckUpdateRequest defines model for DeckUpdateRequest.
type DeckUpdateRequest struct {
	Cards     []DeckCardEntry `json:"cards"`
	DeckName  string          `json:"deck_name"`
	PlaymatNo *int64          `json:"playmat_no,omitempty"`
	SleeveNo  *int64          `json:"sleeve_no,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// PassiveEffect defines model for PassiveEffect.
type PassiveEffect struct {
	Params map[string]interface{} `json:"params"`

	// Type パッシブエフェクトの種別。
	Type PassiveEffectType `json:"type"`
}

// PassiveEffectType パッシブエフェクトの種別。
type PassiveEffectType string

// PlatformEffect defines model for PlatformEffect.
type PlatformEffect struct {
	Params map[string]interface{} `json:"params"`

	// Type プラットフォームエフェクトの種別。
	Type PlatformEffectType `json:"type"`
}

// PlatformEffectType プラットフォームエフェクトの種別。
type PlatformEffectType string

// PlayerCardWithDef プレイヤー所持カードにカード定義フィールドを付加した API レスポンス型。
type PlayerCardWithDef struct {
	ArtNo    int64  `json:"art_no"`
	CardID   string `json:"card_id"`
	CardName string `json:"card_name"`
	CardType string `json:"card_type"`

	// Count 所持枚数
	Count         int             `json:"count"`
	DeployTurns   int64           `json:"deploy_turns"`
	EffectText    *string         `json:"effect_text,omitempty"`
	Elastic       bool            `json:"elastic"`
	Faction       string          `json:"faction"`
	Resizable     bool            `json:"resizable"`
	ResourceLabel string          `json:"resource_label"`
	Restriction   string          `json:"restriction"`
	Stats         json.RawMessage `json:"stats"`
	Subtype       *string         `json:"subtype,omitempty"`
}

// DeckIdPath defines model for DeckIdPath.
type DeckIdPath = int64

// internalAuthContextKey is the context key for InternalAuth security scheme
type internalAuthContextKey string

// CreateDeckJSONRequestBody defines body for CreateDeck for application/json ContentType.
type CreateDeckJSONRequestBody = DeckCreateRequest

// UpdateDeckJSONRequestBody defines body for UpdateDeck for application/json ContentType.
type UpdateDeckJSONRequestBody = DeckUpdateRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListPlayerCards request
	ListPlayerCards(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListCardsWithOwnership request
	ListCardsWithOwnership(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListDecks request
	ListDecks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateDeckWithBody request with any body
	CreateDeckWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateDeck(ctx context.Context, body CreateDeckJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteDeck request
	DeleteDeck(ctx context.Context, deckId DeckIdPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDeck request
	GetDeck(ctx context.Context, deckId DeckIdPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateDeckWithBody request with any body
	UpdateDeckWithBody(ctx context.Context, deckId DeckIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateDeck(ctx context.Context, deckId DeckIdPath, body UpdateDeckJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ValidateDeckForBattle request
	ValidateDeckForBattle(ctx context.Context, deckId DeckIdPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListCards request
	ListCards(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListPlayerCards(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPlayerCardsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListCardsWithOwnership(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCardsWithOwnershipRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListDecks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDecksRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateDeckWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDeckRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateDeck(ctx context.Context, body CreateDeckJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDeckRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteDeck(ctx context.Context, deckId DeckIdPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteDeckRequest(c.Server, deckId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDeck(ctx context.Context, deckId DeckIdPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDeckRequest(c.Server, deckId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateDeckWithBody(ctx context.Context, deckId DeckIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateDeckRequestWithBody(c.Server, deckId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateDeck(ctx context.Context, deckId DeckIdPath, body UpdateDeckJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateDeckRequest(c.Server, deckId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ValidateDeckForBattle(ctx context.Context, deckId DeckIdPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewValidateDeckForBattleRequest(c.Server, deckId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListCards(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCardsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListPlayerCardsRequest generates requests for ListPlayerCards
func NewListPlayerCardsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cards/cards")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListCardsWithOwnershipRequest generates requests for ListCardsWithOwnership
func NewListCardsWithOwnershipRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cards/cards/with-ownership")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListDecksRequest generates requests for ListDecks
func NewListDecksRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cards/decks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateDeckRequest calls the generic CreateDeck builder with application/json body
func NewCreateDeckRequest(server string, body CreateDeckJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateDeckRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateDeckRequestWithBody generates requests for CreateDeck with any type of body
func NewCreateDeckRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cards/decks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteDeckRequest generates requests for DeleteDeck
func NewDeleteDeckRequest(server string, deckId DeckIdPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "deckId", deckId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cards/decks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDeckRequest generates requests for GetDeck
func NewGetDeckRequest(server string, deckId DeckIdPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "deckId", deckId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cards/decks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateDeckRequest calls the generic UpdateDeck builder with application/json body
func NewUpdateDeckRequest(server string, deckId DeckIdPath, body UpdateDeckJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateDeckRequestWithBody(server, deckId, "application/json", bodyReader)
}

// NewUpdateDeckRequestWithBody generates requests for UpdateDeck with any type of body
func NewUpdateDeckRequestWithBody(server string, deckId DeckIdPath, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "deckId", deckId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cards/decks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewValidateDeckForBattleRequest generates requests for ValidateDeckForBattle
func NewValidateDeckForBattleRequest(server string, deckId DeckIdPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "deckId", deckId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cards/decks/%s/validate-for-battle", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListCardsRequest generates requests for ListCards
func NewListCardsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/cards")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListPlayerCardsWithResponse request
	ListPlayerCardsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListPlayerCardsResponse, error)

	// ListCardsWithOwnershipWithResponse request
	ListCardsWithOwnershipWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListCardsWithOwnershipResponse, error)

	// ListDecksWithResponse request
	ListDecksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDecksResponse, error)

	// CreateDeckWithBodyWithResponse request with any body
	CreateDeckWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDeckResponse, error)

	CreateDeckWithResponse(ctx context.Context, body CreateDeckJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDeckResponse, error)

	// DeleteDeckWithResponse request
	DeleteDeckWithResponse(ctx context.Context, deckId DeckIdPath, reqEditors ...RequestEditorFn) (*DeleteDeckResponse, error)

	// GetDeckWithResponse request
	GetDeckWithResponse(ctx context.Context, deckId DeckIdPath, reqEditors ...RequestEditorFn) (*GetDeckResponse, error)

	// UpdateDeckWithBodyWithResponse request with any body
	UpdateDeckWithBodyWithResponse(ctx context.Context, deckId DeckIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateDeckResponse, error)

	UpdateDeckWithResponse(ctx context.Context, deckId DeckIdPath, body UpdateDeckJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateDeckResponse, error)

	// ValidateDeckForBattleWithResponse request
	ValidateDeckForBattleWithResponse(ctx context.Context, deckId DeckIdPath, reqEditors ...RequestEditorFn) (*ValidateDeckForBattleResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// ListCardsWithResponse request
	ListCardsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListCardsResponse, error)
}

type ListPlayerCardsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]PlayerCardWithDef
}

// Status returns HTTPResponse.Status
func (r ListPlayerCardsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPlayerCardsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListPlayerCardsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListCardsWithOwnershipResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]CardWithOwnership
}

// Status returns HTTPResponse.Status
func (r ListCardsWithOwnershipResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListCardsWithOwnershipResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListCardsWithOwnershipResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListDecksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Deck
}

// Status returns HTTPResponse.Status
func (r ListDecksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDecksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListDecksResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateDeckResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Deck
}

// Status returns HTTPResponse.Status
func (r CreateDeckResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateDeckResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateDeckResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteDeckResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteDeckResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteDeckResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteDeckResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetDeckResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DeckDetailResponse
}

// Status returns HTTPResponse.Status
func (r GetDeckResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDeckResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetDeckResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdateDeckResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Deck
}

// Status returns HTTPResponse.Status
func (r UpdateDeckResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateDeckResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateDeckResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ValidateDeckForBattleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r ValidateDeckForBattleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ValidateDeckForBattleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ValidateDeckForBattleResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListCardsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]CardDefinition
}

// Status returns HTTPResponse.Status
func (r ListCardsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListCardsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListCardsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListPlayerCardsWithResponse request returning *ListPlayerCardsResponse
func (c *ClientWithResponses) ListPlayerCardsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListPlayerCardsResponse, error) {
	rsp, err := c.ListPlayerCards(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPlayerCardsResponse(rsp)
}

// ListCardsWithOwnershipWithResponse request returning *ListCardsWithOwnershipResponse
func (c *ClientWithResponses) ListCardsWithOwnershipWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListCardsWithOwnershipResponse, error) {
	rsp, err := c.ListCardsWithOwnership(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCardsWithOwnershipResponse(rsp)
}

// ListDecksWithResponse request returning *ListDecksResponse
func (c *ClientWithResponses) ListDecksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDecksResponse, error) {
	rsp, err := c.ListDecks(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDecksResponse(rsp)
}

// CreateDeckWithBodyWithResponse request with arbitrary body returning *CreateDeckResponse
func (c *ClientWithResponses) CreateDeckWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDeckResponse, error) {
	rsp, err := c.CreateDeckWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDeckResponse(rsp)
}

func (c *ClientWithResponses) CreateDeckWithResponse(ctx context.Context, body CreateDeckJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDeckResponse, error) {
	rsp, err := c.CreateDeck(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDeckResponse(rsp)
}

// DeleteDeckWithResponse request returning *DeleteDeckResponse
func (c *ClientWithResponses) DeleteDeckWithResponse(ctx context.Context, deckId DeckIdPath, reqEditors ...RequestEditorFn) (*DeleteDeckResponse, error) {
	rsp, err := c.DeleteDeck(ctx, deckId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteDeckResponse(rsp)
}

// GetDeckWithResponse request returning *GetDeckResponse
func (c *ClientWithResponses) GetDeckWithResponse(ctx context.Context, deckId DeckIdPath, reqEditors ...RequestEditorFn) (*GetDeckResponse, error) {
	rsp, err := c.GetDeck(ctx, deckId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDeckResponse(rsp)
}

// UpdateDeckWithBodyWithResponse request with arbitrary body returning *UpdateDeckResponse
func (c *ClientWithResponses) UpdateDeckWithBodyWithResponse(ctx context.Context, deckId DeckIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateDeckResponse, error) {
	rsp, err := c.UpdateDeckWithBody(ctx, deckId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateDeckResponse(rsp)
}

func (c *ClientWithResponses) UpdateDeckWithResponse(ctx context.Context, deckId DeckIdPath, body UpdateDeckJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateDeckResponse, error) {
	rsp, err := c.UpdateDeck(ctx, deckId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateDeckResponse(rsp)
}

// ValidateDeckForBattleWithResponse request returning *ValidateDeckForBattleResponse
func (c *ClientWithResponses) ValidateDeckForBattleWithResponse(ctx context.Context, deckId DeckIdPath, reqEditors ...RequestEditorFn) (*ValidateDeckForBattleResponse, error) {
	rsp, err := c.ValidateDeckForBattle(ctx, deckId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseValidateDeckForBattleResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ListCardsWithResponse request returning *ListCardsResponse
func (c *ClientWithResponses) ListCardsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListCardsResponse, error) {
	rsp, err := c.ListCards(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCardsResponse(rsp)
}

// ParseListPlayerCardsResponse parses an HTTP response from a ListPlayerCardsWithResponse call
func ParseListPlayerCardsResponse(rsp *http.Response) (*ListPlayerCardsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPlayerCardsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []PlayerCardWithDef
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListCardsWithOwnershipResponse parses an HTTP response from a ListCardsWithOwnershipWithResponse call
func ParseListCardsWithOwnershipResponse(rsp *http.Response) (*ListCardsWithOwnershipResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListCardsWithOwnershipResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []CardWithOwnership
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListDecksResponse parses an HTTP response from a ListDecksWithResponse call
func ParseListDecksResponse(rsp *http.Response) (*ListDecksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDecksResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Deck
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateDeckResponse parses an HTTP response from a CreateDeckWithResponse call
func ParseCreateDeckResponse(rsp *http.Response) (*CreateDeckResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateDeckResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Deck
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseDeleteDeckResponse parses an HTTP response from a DeleteDeckWithResponse call
func ParseDeleteDeckResponse(rsp *http.Response) (*DeleteDeckResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteDeckResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetDeckResponse parses an HTTP response from a GetDeckWithResponse call
func ParseGetDeckResponse(rsp *http.Response) (*GetDeckResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDeckResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeckDetailResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseUpdateDeckResponse parses an HTTP response from a UpdateDeckWithResponse call
func ParseUpdateDeckResponse(rsp *http.Response) (*UpdateDeckResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateDeckResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Deck
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseValidateDeckForBattleResponse parses an HTTP response from a ValidateDeckForBattleWithResponse call
func ParseValidateDeckForBattleResponse(rsp *http.Response) (*ValidateDeckForBattleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ValidateDeckForBattleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListCardsResponse parses an HTTP response from a ListCardsWithResponse call
func ParseListCardsResponse(rsp *http.Response) (*ListCardsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListCardsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []CardDefinition
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
