// Package apicard provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apicard

import (
	"encoding/json"
	"time"
)

const (
	InternalAuthScopes internalAuthContextKey = "InternalAuth.Scopes"
)

// Defines values for AttachmentEffectType.
const (
	AttachmentEffectTypeStatBonus AttachmentEffectType = "stat_bonus"
)

// Valid indicates whether the value is a known member of the AttachmentEffectType enum.
func (e AttachmentEffectType) Valid() bool {
	switch e {
	case AttachmentEffectTypeStatBonus:
		return true
	default:
		return false
	}
}

// Defines values for PassiveEffectType.
const (
	PassiveEffectTypeAvBonus             PassiveEffectType = "av_bonus"
	PassiveEffectTypeDvIfCardOnField     PassiveEffectType = "dv_if_card_on_field"
	PassiveEffectTypeDvPerOtherDb        PassiveEffectType = "dv_per_other_db"
	PassiveEffectTypeScaleCostFree       PassiveEffectType = "scale_cost_free"
	PassiveEffectTypeTpIfCardTypeOnField PassiveEffectType = "tp_if_card_type_on_field"
	PassiveEffectTypeTpPerBackendData    PassiveEffectType = "tp_per_backend_data"
	PassiveEffectTypeTpPerBackendDb      PassiveEffectType = "tp_per_backend_db"
)

// Valid indicates whether the value is a known member of the PassiveEffectType enum.
func (e PassiveEffectType) Valid() bool {
	switch e {
	case PassiveEffectTypeAvBonus:
		return true
	case PassiveEffectTypeDvIfCardOnField:
		return true
	case PassiveEffectTypeDvPerOtherDb:
		return true
	case PassiveEffectTypeScaleCostFree:
		return true
	case PassiveEffectTypeTpIfCardTypeOnField:
		return true
	case PassiveEffectTypeTpPerBackendData:
		return true
	case PassiveEffectTypeTpPerBackendDb:
		return true
	default:
		return false
	}
}

// Defines values for PlatformEffectType.
const (
	PlatformEffectTypeAvBonus    PlatformEffectType = "av_bonus"
	PlatformEffectTypeTpBonus    PlatformEffectType = "tp_bonus"
	PlatformEffectTypeYieldBonus PlatformEffectType = "yield_bonus"
)

// Valid indicates whether the value is a known member of the PlatformEffectType enum.
func (e PlatformEffectType) Valid() bool {
	switch e {
	case PlatformEffectTypeAvBonus:
		return true
	case PlatformEffectTypeTpBonus:
		return true
	case PlatformEffectTypeYieldBonus:
		return true
	default:
		return false
	}
}

// AttachmentEffect defines model for AttachmentEffect.
type AttachmentEffect struct {
	Params map[string]interface{} `json:"params"`

	// Type アタッチメントエフェクトの種別。
	Type AttachmentEffectType `json:"type"`
}

// AttachmentEffectType アタッチメントエフェクトの種別。
type AttachmentEffectType string

// CardDefinition defines model for CardDefinition.
type CardDefinition struct {
	AttachmentEffects *[]AttachmentEffect `json:"attachment_effects,omitempty"`
	CardID            string              `json:"card_id"`
	CardName          string              `json:"card_name"`

	// CardType カード種別
	CardType       string    `json:"card_type"`
	CostPerRequest *int64    `json:"cost_per_request,omitempty"`
	CreatedAt      time.Time `json:"created_at"`

	// DeployTurns デプロイターン数 (0=即時)
	DeployTurns int64   `json:"deploy_turns"`
	EffectText  *string `json:"effect_text,omitempty"`

	// Effects エフェクト定義 JSON
	Effects *json.RawMessage `json:"effects,omitempty"`

	// Elastic 自動スケール対応か
	Elastic          bool   `json:"elastic"`
	ElasticIncrement *int64 `json:"elastic_increment,omitempty"`

	// Faction ファクション (`SHE` / `Tenki` / `Sugar` / `Tuners` / `Neutral`)
	Faction         string            `json:"faction"`
	FreeTier        *int64            `json:"free_tier,omitempty"`
	IsActive        bool              `json:"is_active"`
	PassiveEffects  *[]PassiveEffect  `json:"passive_effects,omitempty"`
	PlatformEffects *[]PlatformEffect `json:"platform_effects,omitempty"`

	// Resizable 手動スケール可能か
	Resizable     bool   `json:"resizable"`
	ResourceLabel string `json:"resource_label"`

	// Restriction 制限区分 (`unlimited` / `semi_limited` / `limited` / `forbidden`)
	Restriction string `json:"restriction"`

	// Stats スタッツ (ComputeStats または DataStats)
	Stats json.RawMessage `json:"stats"`

	// Subtype サブタイプ (Compute/Data 配下のみ)
	Subtype   *string   `json:"subtype,omitempty"`
	UpdatedAt time.Time `json:"updated_at"`
}

// CardWithOwnership CardDefinition にプレイヤー所持状態を付与した型。
type CardWithOwnership struct {
	AttachmentEffects *[]AttachmentEffect `json:"attachment_effects,omitempty"`
	CardID            string              `json:"card_id"`
	CardName          string              `json:"card_name"`
	CardType          string              `json:"card_type"`
	CostPerRequest    *int64              `json:"cost_per_request,omitempty"`
	CreatedAt         time.Time           `json:"created_at"`
	DeployTurns       int64               `json:"deploy_turns"`
	EffectText        *string             `json:"effect_text,omitempty"`
	Effects           *json.RawMessage    `json:"effects,omitempty"`
	Elastic           bool                `json:"elastic"`
	ElasticIncrement  *int64              `json:"elastic_increment,omitempty"`
	Faction           string              `json:"faction"`
	FreeTier          *int64              `json:"free_tier,omitempty"`
	IsActive          bool                `json:"is_active"`
	IsOwned           bool                `json:"is_owned"`
	PassiveEffects    *[]PassiveEffect    `json:"passive_effects,omitempty"`
	PlatformEffects   *[]PlatformEffect   `json:"platform_effects,omitempty"`
	Resizable         bool                `json:"resizable"`
	ResourceLabel     string              `json:"resource_label"`
	Restriction       string              `json:"restriction"`
	Stats             json.RawMessage     `json:"stats"`
	Subtype           *string             `json:"subtype,omitempty"`
	UpdatedAt         time.Time           `json:"updated_at"`
}

// ComputeStats Compute / Container / Orchestrator / Serverless / AI/ML カード用スタッツ。
type ComputeStats struct {
	Availability    int64  `json:"availability"`
	MaintenanceCost int64  `json:"maintenance_cost"`
	SLAPenalty      int64  `json:"sla_penalty"`
	Throughput      int64  `json:"throughput"`
	ThroughputMax   *int64 `json:"throughput_max,omitempty"`
}

// DataStats Database / ObjectStorage / CacheDB カード用スタッツ。
type DataStats struct {
	Availability    int64  `json:"availability"`
	MaintenanceCost int64  `json:"maintenance_cost"`
	SLAPenalty      int64  `json:"sla_penalty"`
	Yield           int64  `json:"yield"`
	YieldMax        *int64 `json:"yield_max,omitempty"`
}

// Deck プレイヤーのデッキ (カード構成オプショナル)。
type Deck struct {
	CreatedAt time.Time `json:"created_at"`

	// DeckCards デッキのカード構成 (API レスポンス時に populate)
	DeckCards *[]DeckCard `json:"deck_cards,omitempty"`

	// DeckID デッキ ID (自動採番)
	DeckID   int64  `json:"deck_id"`
	DeckName string `json:"deck_name"`

	// IsValid バトル使用可能か (都度算出)
	IsValid   bool      `json:"is_valid"`
	PlayerID  string    `json:"player_id"`
	PlaymatNo *int64    `json:"playmat_no,omitempty"`
	SleeveNo  *int64    `json:"sleeve_no,omitempty"`
	UpdatedAt time.Time `json:"updated_at"`
}

// DeckCard defines model for DeckCard.
type DeckCard struct {
	ArtNo    int64  `json:"art_no"`
	CardID   string `json:"card_id"`
	Count    int    `json:"count"`
	DeckID   int64  `json:"deck_id"`
	PlayerID string `json:"player_id"`
}

// DeckCardEntry デッキ作成・更新リクエスト内のカードエントリ。
type DeckCardEntry struct {
	ArtNo  int64  `json:"art_no"`
	CardID string `json:"card_id"`
	Count  int    `json:"count"`
}

// DeckCreateRequest defines model for DeckCreateRequest.
type DeckCreateRequest struct {
	Cards     []DeckCardEntry `json:"cards"`
	DeckName  string          `json:"deck_name"`
	PlaymatNo *int64          `json:"playmat_no,omitempty"`
	SleeveNo  *int64          `json:"sleeve_no,omitempty"`
}

// DeckDetailResponse GET /players/{playerId}/decks/{deckId} のレスポンス封筒。
type DeckDetailResponse struct {
	Cards []DeckCard `json:"cards"`

	// Deck プレイヤーのデッキ (カード構成オプショナル)。
	Deck Deck `json:"deck"`
}

// DeckUpdateRequest defines model for DeckUpdateRequest.
type DeckUpdateRequest struct {
	Cards     []DeckCardEntry `json:"cards"`
	DeckName  string          `json:"deck_name"`
	PlaymatNo *int64          `json:"playmat_no,omitempty"`
	SleeveNo  *int64          `json:"sleeve_no,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// PassiveEffect defines model for PassiveEffect.
type PassiveEffect struct {
	Params map[string]interface{} `json:"params"`

	// Type パッシブエフェクトの種別。
	Type PassiveEffectType `json:"type"`
}

// PassiveEffectType パッシブエフェクトの種別。
type PassiveEffectType string

// PlatformEffect defines model for PlatformEffect.
type PlatformEffect struct {
	Params map[string]interface{} `json:"params"`

	// Type プラットフォームエフェクトの種別。
	Type PlatformEffectType `json:"type"`
}

// PlatformEffectType プラットフォームエフェクトの種別。
type PlatformEffectType string

// PlayerCardWithDef プレイヤー所持カードにカード定義フィールドを付加した API レスポンス型。
type PlayerCardWithDef struct {
	ArtNo    int64  `json:"art_no"`
	CardID   string `json:"card_id"`
	CardName string `json:"card_name"`
	CardType string `json:"card_type"`

	// Count 所持枚数
	Count         int             `json:"count"`
	DeployTurns   int64           `json:"deploy_turns"`
	EffectText    *string         `json:"effect_text,omitempty"`
	Elastic       bool            `json:"elastic"`
	Faction       string          `json:"faction"`
	Resizable     bool            `json:"resizable"`
	ResourceLabel string          `json:"resource_label"`
	Restriction   string          `json:"restriction"`
	Stats         json.RawMessage `json:"stats"`
	Subtype       *string         `json:"subtype,omitempty"`
}

// DeckIdPath defines model for DeckIdPath.
type DeckIdPath = int64

// internalAuthContextKey is the context key for InternalAuth security scheme
type internalAuthContextKey string

// CreateDeckJSONRequestBody defines body for CreateDeck for application/json ContentType.
type CreateDeckJSONRequestBody = DeckCreateRequest

// UpdateDeckJSONRequestBody defines body for UpdateDeck for application/json ContentType.
type UpdateDeckJSONRequestBody = DeckUpdateRequest
