// Code generated by scripts/generate_types.py; DO NOT EDIT.

package apicard

type PassiveEffectType = string
type PlatformEffectType = string
type AttachmentEffectType = string

const (
	PassiveTPPerBackendDB PassiveEffectType = "tp_per_backend_db"
	PassiveTPPerBackendData PassiveEffectType = "tp_per_backend_data"
	PassiveTPIfCardTypeOnField PassiveEffectType = "tp_if_card_type_on_field"
	PassiveYieldPerOtherDB PassiveEffectType = "dv_per_other_db"
	PassiveYieldIfCardOnField PassiveEffectType = "dv_if_card_on_field"
	PassiveAVBonus PassiveEffectType = "av_bonus"
	PassiveScaleCostFree PassiveEffectType = "scale_cost_free"
)

const (
	PlatformTPBonus PlatformEffectType = "tp_bonus"
	PlatformYieldBonus PlatformEffectType = "yield_bonus"
	PlatformAVBonus PlatformEffectType = "av_bonus"
)

const (
	AttachmentStatBonus AttachmentEffectType = "stat_bonus"
)

type PassiveEffect struct {
	Type   PassiveEffectType      `json:"type"`
	Params map[string]interface{} `json:"params"`
}

type PlatformEffect struct {
	Type   PlatformEffectType     `json:"type"`
	Params map[string]interface{} `json:"params"`
}

type AttachmentEffect struct {
	Type   AttachmentEffectType   `json:"type"`
	Params map[string]interface{} `json:"params"`
}

