-- Auto-generated by scripts/generate_card_packs.py. DO NOT EDIT.

INSERT INTO card.card_pack
  (pack_id, description, selection, copies_per_card, is_active)
VALUES
  ('initial_she', 'オンボーディング初期パック (SHE 選択時)', '{"type":"by_factions","factions":["SHE","Neutral"]}'::jsonb, 3, true),
  ('initial_tenki', 'オンボーディング初期パック (Tenki 選択時)', '{"type":"by_factions","factions":["Tenki","Neutral"]}'::jsonb, 3, true),
  ('initial_sugar', 'オンボーディング初期パック (Sugar 選択時)', '{"type":"by_factions","factions":["Sugar","Neutral"]}'::jsonb, 3, true),
  ('initial_tuners', 'オンボーディング初期パック (Tuners 選択時)', '{"type":"by_factions","factions":["Tuners","Neutral"]}'::jsonb, 3, true),
  ('faction_set_she', 'ショップ faction_set 商品 (SHE)', '{"type":"by_factions","factions":["SHE"]}'::jsonb, 3, true),
  ('faction_set_tenki', 'ショップ faction_set 商品 (Tenki)', '{"type":"by_factions","factions":["Tenki"]}'::jsonb, 3, true),
  ('faction_set_sugar', 'ショップ faction_set 商品 (Sugar)', '{"type":"by_factions","factions":["Sugar"]}'::jsonb, 3, true),
  ('faction_set_tuners', 'ショップ faction_set 商品 (Tuners)', '{"type":"by_factions","factions":["Tuners"]}'::jsonb, 3, true)
ON CONFLICT (pack_id) DO UPDATE SET
  description     = EXCLUDED.description,
  selection       = EXCLUDED.selection,
  copies_per_card = EXCLUDED.copies_per_card,
  is_active       = EXCLUDED.is_active;
