-- Auto-generated by scripts/generate_card_packs.py. DO NOT EDIT.

INSERT INTO card.card_pack
  (pack_id, description, selection, copies_per_card, is_active)
VALUES
  ('basic', '全プレイヤー共通の Neutral 基本セット', '{"type":"by_factions","factions":["Neutral"]}'::jsonb, 3, true),
  ('faction_set_she', 'SHE 基本セット', '{"type":"by_factions","factions":["SHE"]}'::jsonb, 3, true),
  ('faction_set_tenki', 'Tenki 基本セット', '{"type":"by_factions","factions":["Tenki"]}'::jsonb, 3, true),
  ('faction_set_sugar', 'Sugar 基本セット', '{"type":"by_factions","factions":["Sugar"]}'::jsonb, 3, true),
  ('faction_set_tuners', 'Tuners 基本セット', '{"type":"by_factions","factions":["Tuners"]}'::jsonb, 3, true)
ON CONFLICT (pack_id) DO UPDATE SET
  description     = EXCLUDED.description,
  selection       = EXCLUDED.selection,
  copies_per_card = EXCLUDED.copies_per_card,
  is_active       = EXCLUDED.is_active;
