-- Auto-generated by scripts/generate_products.py. DO NOT EDIT.

INSERT INTO card.products (product_id, faction, product_name, is_active)
VALUES
  ('PD-0001', 'SHE', 'ECサイト', true),
  ('PD-0002', 'Tenki', '天気予報アプリ', true),
  ('PD-0003', 'Sugar', 'レシピアプリ', true),
  ('PD-0004', 'Tuners', '音楽配信サイト', true)
ON CONFLICT (product_id) DO UPDATE SET
  faction      = EXCLUDED.faction,
  product_name = EXCLUDED.product_name,
  is_active    = EXCLUDED.is_active,
  updated_at   = now();

