-- Auto-generated by scripts/generate_products.py. DO NOT EDIT.

INSERT INTO card.products (product_id, faction, product_name)
VALUES
  ('PD-0001', 'SHE', 'ECサイト'),
  ('PD-0002', 'Tenki', '天気予報アプリ'),
  ('PD-0003', 'Sugar', 'レシピアプリ'),
  ('PD-0004', 'Tuners', '音楽配信サイト')
ON CONFLICT (product_id) DO UPDATE SET
  faction      = EXCLUDED.faction,
  product_name = EXCLUDED.product_name,
  updated_at   = now();

