#!/usr/bin/env python3
"""Generate card pack seed SQL from data/card_packs.yaml.

Outputs:
  - db/seed/card_packs_seed.sql  (PostgreSQL UPSERT seed for card.card_pack)

Usage:
    python3 scripts/generate_card_packs.py

`data/card_packs.yaml` is the SSoT. The output SQL is regenerated each run and
must not be edited by hand.
"""

import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent
YAML_IN = ROOT / "data" / "card_packs.yaml"
SEED_OUT = ROOT / "db" / "seed" / "card_packs_seed.sql"

VALID_SELECTION_TYPES = {"by_factions", "by_card_ids"}
VALID_FACTIONS = {"SHE", "Tenki", "Sugar", "Tuners", "Neutral"}


def load_packs() -> list[dict]:
    with YAML_IN.open(encoding="utf-8") as f:
        data = yaml.safe_load(f)
    if not isinstance(data, dict) or "packs" not in data:
        raise ValueError(f"{YAML_IN}: top-level 'packs' key is required")
    return data["packs"]


def validate(packs: list[dict]) -> None:
    seen_ids: set[str] = set()
    for pack in packs:
        pid = pack.get("pack_id")
        if not isinstance(pid, str) or not pid:
            raise ValueError(f"pack_id must be a non-empty string: {pack!r}")
        if pid in seen_ids:
            raise ValueError(f"duplicate pack_id: {pid}")
        seen_ids.add(pid)

        copies = pack.get("copies_per_card")
        if not isinstance(copies, int) or copies <= 0:
            raise ValueError(f"{pid}: copies_per_card must be a positive int, got {copies!r}")

        sel = pack.get("selection")
        if not isinstance(sel, dict):
            raise ValueError(f"{pid}: selection must be an object")
        stype = sel.get("type")
        if stype not in VALID_SELECTION_TYPES:
            raise ValueError(
                f"{pid}: selection.type must be one of {sorted(VALID_SELECTION_TYPES)}, got {stype!r}"
            )
        if stype == "by_factions":
            factions = sel.get("factions")
            if not isinstance(factions, list) or not factions:
                raise ValueError(f"{pid}: selection.factions must be a non-empty list")
            unknown = [f for f in factions if f not in VALID_FACTIONS]
            if unknown:
                raise ValueError(
                    f"{pid}: unknown faction(s) {unknown}; allowed = {sorted(VALID_FACTIONS)}"
                )
        elif stype == "by_card_ids":
            card_ids = sel.get("card_ids")
            if not isinstance(card_ids, list) or not card_ids:
                raise ValueError(f"{pid}: selection.card_ids must be a non-empty list")
            for cid in card_ids:
                if not isinstance(cid, str) or not cid:
                    raise ValueError(f"{pid}: card_ids entries must be non-empty strings")


def sql_quote(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def render_seed(packs: list[dict]) -> str:
    lines = [
        "-- Auto-generated by scripts/generate_card_packs.py. DO NOT EDIT.",
        "",
        "INSERT INTO card.card_pack",
        "  (pack_id, description, selection, copies_per_card, is_active)",
        "VALUES",
    ]
    rows = []
    for pack in packs:
        pid = pack["pack_id"]
        desc = pack.get("description") or ""
        sel_json = json.dumps(pack["selection"], ensure_ascii=False, separators=(",", ":"))
        copies = pack["copies_per_card"]
        is_active = pack.get("is_active", True)
        row = (
            f"  ({sql_quote(pid)}, {sql_quote(desc)}, "
            f"{sql_quote(sel_json)}::jsonb, {copies}, {'true' if is_active else 'false'})"
        )
        rows.append(row)
    lines.append(",\n".join(rows))
    lines.append("ON CONFLICT (pack_id) DO UPDATE SET")
    lines.append("  description     = EXCLUDED.description,")
    lines.append("  selection       = EXCLUDED.selection,")
    lines.append("  copies_per_card = EXCLUDED.copies_per_card,")
    lines.append("  is_active       = EXCLUDED.is_active;")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    packs = load_packs()
    validate(packs)
    SEED_OUT.parent.mkdir(parents=True, exist_ok=True)
    SEED_OUT.write_text(render_seed(packs), encoding="utf-8")
    print(f"Wrote {SEED_OUT.relative_to(ROOT)} ({len(packs)} packs)")


if __name__ == "__main__":
    main()
