#!/usr/bin/env python3
"""Generate card pack seed SQL from data/card_packs.yaml.

Outputs:
  - db/seed/card_packs_seed.sql  (PostgreSQL UPSERT seed for card.card_pack
                                   and card.card_pack_cards)

Usage:
    python3 scripts/generate_card_packs.py

`data/card_packs.yaml` is the SSoT. The output SQL is regenerated each run and
must not be edited by hand.
"""

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent
YAML_IN = ROOT / "data" / "card_packs.yaml"
SEED_OUT = ROOT / "db" / "seed" / "card_packs_seed.sql"


def load_packs() -> list[dict]:
    with YAML_IN.open(encoding="utf-8") as f:
        data = yaml.safe_load(f)
    if not isinstance(data, dict) or "packs" not in data:
        raise ValueError(f"{YAML_IN}: top-level 'packs' key is required")
    return data["packs"]


def validate(packs: list[dict]) -> None:
    seen_ids: set[str] = set()
    for pack in packs:
        pid = pack.get("pack_id")
        if not isinstance(pid, str) or not pid:
            raise ValueError(f"pack_id must be a non-empty string: {pack!r}")
        if pid in seen_ids:
            raise ValueError(f"duplicate pack_id: {pid}")
        seen_ids.add(pid)

        cards = pack.get("cards")
        if not isinstance(cards, dict) or not cards:
            raise ValueError(f"{pid}: cards must be a non-empty mapping of card_id -> copies")
        for cid, copies in cards.items():
            if not isinstance(cid, str) or not cid:
                raise ValueError(f"{pid}: card_id must be a non-empty string, got {cid!r}")
            if not isinstance(copies, int) or copies <= 0:
                raise ValueError(
                    f"{pid}/{cid}: copies must be a positive int, got {copies!r}"
                )


def sql_quote(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def render_seed(packs: list[dict]) -> str:
    lines = ["-- Auto-generated by scripts/generate_card_packs.py. DO NOT EDIT.", ""]

    pack_rows = []
    for pack in packs:
        pid = pack["pack_id"]
        desc = pack.get("description") or ""
        is_active = pack.get("is_active", True)
        pack_rows.append(
            f"  ({sql_quote(pid)}, {sql_quote(desc)}, {'true' if is_active else 'false'})"
        )

    lines.append("INSERT INTO card.card_pack (pack_id, description, is_active)")
    lines.append("VALUES")
    lines.append(",\n".join(pack_rows))
    lines.append("ON CONFLICT (pack_id) DO UPDATE SET")
    lines.append("  description = EXCLUDED.description,")
    lines.append("  is_active   = EXCLUDED.is_active;")
    lines.append("")

    pack_card_rows = []
    pack_ids = []
    for pack in packs:
        pid = pack["pack_id"]
        pack_ids.append(pid)
        for cid, copies in pack["cards"].items():
            pack_card_rows.append(
                f"  ({sql_quote(pid)}, {sql_quote(cid)}, {copies})"
            )

    lines.append("-- Replace the entire card_pack_cards rows for the listed packs:")
    lines.append("-- delete current rows for those packs, then INSERT the seed rows.")
    pack_id_list = ", ".join(sql_quote(p) for p in pack_ids)
    lines.append(f"DELETE FROM card.card_pack_cards WHERE pack_id IN ({pack_id_list});")
    lines.append("")
    lines.append("INSERT INTO card.card_pack_cards (pack_id, card_id, copies)")
    lines.append("VALUES")
    lines.append(",\n".join(pack_card_rows) + ";")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    packs = load_packs()
    validate(packs)
    SEED_OUT.parent.mkdir(parents=True, exist_ok=True)
    SEED_OUT.write_text(render_seed(packs), encoding="utf-8")
    total_cards = sum(len(p["cards"]) for p in packs)
    print(f"Wrote {SEED_OUT.relative_to(ROOT)} ({len(packs)} packs, {total_cards} pack-card rows)")


if __name__ == "__main__":
    main()
